baseURL = "http://kutekai.com/"
languageCode = "en"
title = "Kutekai"
themesDir = "themes"
theme = "hugo-hero-theme"
publishDir = "kutekai.github.io"

[params]
  google_analytics_id="UA-127057347-2"

  [params.homepage_meta_tags]
    meta_description = "Kutekai is an AWS Cloud Consultancy providing Solution Design & implementation, Infrastructure Automation, Proserve and Management"
    meta_og_title = "Kutekai"
    meta_og_type = "website"
    meta_og_url = "http://kutekai.com"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

#[[menu.main]]
#    name = "Work"
#    url = "/work/"
#    weight = 2
#
#[[menu.main]]
#    name = "About"
#    url = "/about/"
#    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
